FROM ubuntu

RUN apt update && apt upgrade -y && \
    apt install samba smbclient winbind libpam-winbind \
    libnss-winbind krb5-kdc libpam-krb5 \
    vim iproute2 dnsutils iputils-ping netcat -y && \
    apt clean autoclean && \
    apt autoremove -y && \
    mv /etc/samba/smb.conf /etc/samba/smb.ORIG.conf

WORKDIR /usr/local/sbin
COPY sbin /usr/local/sbin
CMD bash -c "samba-domain-provision && samba -F"
EXPOSE 53 88 123/udp 137/udp 138/udp 139 389 445 464 636 3268 3269 49152-65535
