#!/bin/bash
# Exit if any error
set -e

# krb5 file compiled and from mirror has different location
KRB5_FROM_MIRROR='/var/lib/samba/private/krb5.conf'
KRB5_COMPILED='/usr/local/samba/private/krb5.conf'
[ -f ${KRB5_FROM_MIRROR} ] && cat ${KRB5_FROM_MIRROR} > /etc/krb5.conf
[ -f ${KRB5_COMPILED} ] && cat ${KRB5_COMPILED} > /etc/krb5.conf

SERVER_IP=$(ip a | grep 'scope global' | awk '{print $2}' | awk -F / '{print $1}')

echo -e "namerserver ${SERVER_IP}\nsearch ${SEARCH_DOMAIN}" > /etc/resolv.conf

echo -e "127.0.0.1 localhost localhost.localdomain" > /etc/hosts
echo -e "${SERVER_IP} $(hostname).${SEARCH_DOMAIN} $(hostname)" >> /etc/hosts
