#!/usr/bin/env bash

# Exit if any error
set -euo pipefail

until ping -c1 localhost >/dev/null 2>&1; do
  echo "Waiting 5 seconds for localhost ping response response.."
  sleep 5
done

# Skip domain provision if secrets exists
if [[ ! -e "${SAMBA_PATH:-/usr/local/samba}/private/secrets.keytab" ]]; then
  samba-tool domain provision \
    --server-role="${SERVER_ROLE}" \
    --use-rfc2307 \
    --dns-backend="${DNS_BACKEND}" \
    --realm="${REALM}" \
    --domain="${DOMAIN}" \
    --adminpass="${ADMIN_PASS}" \
    --option="dns forwarder=${DNS_FORWARDER}"
fi

update-etc-files