#!/bin/bash
# Exit if any error
set -e

samba-tool domain join ${REALM} ${SERVER_ROLE} \
  --server=dc1 \
  --username=administrator \
  --password=${ADMIN_PASS} \
  --dns-backend=${DNS_BACKEND} \
  --option="dns forwarder=${DNS_FORWARDER}"

update-etc-files
