#!/usr/bin/env bash

# Exit if any error
set -euo pipefail

test "${#}" -ge 1 || { echo "Usage: samba-domain-join <server>"; exit 1; }

samba-tool domain join "${REALM}" "${SERVER_ROLE}" \
  --server="${1}" \
  --username=administrator \
  --password="${ADMIN_PASS}" \
  --dns-backend="${DNS_BACKEND}" \
  --option="dns forwarder=${DNS_FORWARDER}" || true

update-etc-files
