#!/usr/bin/env bash

# Exit if any error
set -euo pipefail

# Require DC as argument
test "${#}" -ge 1 || { echo "Usage: samba-domain-join <server>"; exit 1; }
server="${1}"

if [[ ! -e "${SAMBA_PATH:-/usr/local/samba}/private/secrets.keytab" ]]; then

  # Wait until dc LDAP response
  until nc -z "${server}" 389; do
    echo "Waiting for ${server} LDAP response.."
    sleep 1
  done

  samba-tool domain join "${REALM}" "${SERVER_ROLE:-dc}" \
    --server="${server}" \
    --username=administrator \
    --password="${ADMIN_PASS}" \
    --dns-backend="${DNS_BACKEND:-SAMBA_INTERNAL}" \
    --option="dns forwarder=${DNS_FORWARDER}" || \
  echo "Skipping domain join.."
  
fi

update-etc-files
